# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bot-Creator
email: contact@ketsuna.com
description: >- # this means to ignore newlines until "baseurl:"
  Bot-Creator is a free and open-source platform that allows you to create
  Discord bots without any coding knowledge. It is designed to be user-friendly
  and accessible to everyone, regardless of their technical background.
  With Bot-Creator, you can easily create and customize your own Discord bots
  using a simple drag-and-drop interface.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bot-creator.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: garder500
github_username:  garder500
author: Garder500

# Build settings
ignore_theme_config: true
# theme: minima
plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

postcss:
  cache: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5  # Posts per page
paginate_path: "/blog/page:num/"

future: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - devenv.nix
  - devenv.lock
  - postcss.config.js
  - tailwind.config.js
  - README.md

