const fs = require('fs');
const path = require('path');

const docsDir = '/home/jeremy/Code/vitrine/_docs';

const files = fs.readdirSync(docsDir)
  .filter(f => f.endsWith('.md'))
  .sort()
  .filter(f => f >= 'addactionrow.md' && f <= 'executiontime.md');

// Fix remaining French patterns - ORDERED by length (longest first)
const fixes = [
  // === Multi-word phrases first ===
  [/^description: Définit l'auteur d'un embed Discord\. L'auteur apparaît tout en haut de l'embed, au-dessus du titre, avec une icône et un lien optionnels\./gm, 'description: Sets the author of a Discord embed. The author appears at the very top of the embed, above the title, with an optional icon and link.'],
  [/^Définit l'auteur d'un embed Discord\./gm, 'Sets the author of a Discord embed.'],
  [/Démarre une nouvelle ligne d'action \(action row\) pour contenir des boutons ou des menus de sélection\./g, 'Starts a new action row to contain buttons or select menus.'],
  [/Démarre une nouvelle action row pour contenir of buttons ou des select menus\./g, 'Starts a new action row to contain buttons or select menus.'],
  [/Identifiant personnalisé pour l'interaction/g, 'Custom identifier for the interaction'],
  [/Identifiant personnalisé pour gérer le clic/g, 'Custom identifier to handle clicks'],
  [/Identifiant personnalisé pour la ligne d'action/g, 'Custom identifier for the action row'],
  [/Identifiant personnalisé/g, 'Custom identifier'],
  [/identifiant personnalisé/g, 'custom identifier'],
  [/Identifiant unique pour récupérer/g, 'Unique identifier to retrieve'],
  [/Identifiant unique du groupe/g, 'Unique identifier of the group'],
  [/Identifiant unique/g, 'Unique identifier'],
  [/identifiant unique/g, 'unique identifier'],
  [/Identifiant optionnel de la/g, 'Optional identifier for the'],
  [/Identifiant optionnel/g, 'Optional identifier'],
  [/identifiant optionnel/g, 'optional identifier'],
  [/Identifiant du conteneur/g, 'Container identifier'],
  [/Identifiant de la galerie/g, 'Gallery identifier'],
  [/Identifiant du groupe parent/g, 'Identifier of the parent group'],
  
  // La fonction patterns
  [/La fonction `\$([^`]+)` (permet de |permet d')([^.]+)\./g, 'The `$$$1` function allows $3.'],
  [/The `\$([^`]+)` (permet de |permet d')([^.]+)\./g, 'The `$$$1` function allows $3.'],
  [/La fonction `\$([^`]+)` ([^.]+)\./g, 'The `$$$1` function $2.'],
  [/La fonction `([^`]+)` bannit a user of the server Discord\./g, 'The `$1` function bans a user from the Discord server.'],
  [/La fonction `([^`]+)`/g, 'The `$1` function'],
  [/La fonction \$([^\s]+)/g, 'The $$$1 function'],
  
  // Text displayed patterns
  [/Texte affiché quand rien n'est sélectionné/g, 'Text displayed when nothing is selected'],
  [/Texte affiché sur le bouton/g, 'Text displayed on the button'],
  [/Texte affiché dans le champ/g, 'Text displayed in the field'],
  [/Texte affiché pour cette option/g, 'Text displayed for this option'],
  [/Texte affiché à côté de la case/g, 'Text displayed next to the checkbox'],
  [/Texte affiché/g, 'Text displayed'],
  [/texte affiché/g, 'text displayed'],
  
  // Labels
  [/Étiquette descriptive au-dessus du groupe/g, 'Descriptive label above the group'],
  [/Étiquette descriptive/g, 'Descriptive label'],
  [/Label affiché au-dessus du champ/g, 'Label displayed above the field'],
  [/Label affiché au-dessus/g, 'Label displayed above'],
  
  // URLs
  [/URL de l'image/g, 'Image URL'],
  [/URL de l'image d'avatar/g, 'Avatar image URL'],
  [/URL du fichier à joindre/g, 'URL of the file to attach'],
  [/URL du fichier/g, 'File URL'],
  [/URL de destination/g, 'Destination URL'],
  [/L'URL de l'image/g, 'The image URL'],
  [/L'URL du fichier/g, 'The file URL'],
  [/L'URL doit être accessible publiquement/g, 'The URL must be publicly accessible'],
  [/L'URL doit pointer directement vers une image/g, 'The URL must point directly to an image'],
  [/L'URL doit pointer/g, 'The URL must point'],
  [/L'URL doit/g, 'The URL must'],
  
  // Names
  [/Le nom de l'emoji/g, 'The emoji name'],
  [/Le nom de l'auteur/g, 'The author name'],
  [/Le nom ne doit contenir que/g, 'The name must only contain'],
  [/Le nom doit faire/g, 'The name must be'],
  [/Le nom doit/g, 'The name must'],
  [/le nom devient/g, 'the name becomes'],
  [/le nom de l'auteur/g, 'the author name'],
  [/Nom du fichier/g, 'File name'],
  [/nom du fichier/g, 'file name'],
  
  // Verbs that were missed
  [/Démarre une /g, 'Starts a '],
  [/Définit l'auteur/g, 'Sets the author'],
  [/Définit la ligne/g, 'Sets the line'],
  [/Définit le /g, 'Sets the '],
  [/Définit la /g, 'Sets the '],
  [/Définit l'/g, 'Sets the '],
  [/Bannit un utilisateur of the server/g, 'Bans a user from the server'],
  [/Bannit a user of the server/g, 'Bans a user from the server'],
  [/Bannit l'utilisateur/g, 'Bans the user'],
  [/Bannit le /g, 'Bans the '],
  [/bannit un utilisateur/g, 'bans a user'],
  [/bannit l'utilisateur/g, 'bans the user'],
  [/bannit le /g, 'bans the '],
  [/bannit la /g, 'bans the '],
  [/Retourne le temps d'exécution/g, 'Returns the execution time'],
  [/Retourne le /g, 'Returns the '],
  [/Retourne la /g, 'Returns the '],
  [/Retourne l'/g, 'Returns the '],
  [/retourne le /g, 'returns the '],
  [/retourne la /g, 'returns the '],
  [/retourne l'/g, 'returns the '],
  [/Mesure le temps d'exécution/g, 'Measures the execution time'],
  [/Mesure le temps/g, 'Measures the time'],
  [/Mesure le /g, 'Measures the '],
  [/Mesure la /g, 'Measures the '],
  [/mesure le temps/g, 'measures the time'],
  [/mesure le /g, 'measures the '],
  [/Récupère le /g, 'Retrieves the '],
  [/Récupère la /g, 'Retrieves the '],
  [/Récupère l'/g, 'Retrieves the '],
  [/récupère le /g, 'retrieves the '],
  [/Vérifie si /g, 'Checks if '],
  [/Vérifie l'existence/g, 'Checks the existence'],
  [/vérifie si /g, 'checks if '],
  [/vérifie l'existence/g, 'checks the existence'],
  [/Supprime le /g, 'Deletes the '],
  [/Supprime la /g, 'Deletes the '],
  [/supprime le /g, 'deletes the '],
  [/Calcule le /g, 'Calculates the '],
  [/calcule le /g, 'calculates the '],
  [/Convertit le /g, 'Converts the '],
  [/convertit le /g, 'converts the '],
  [/Formate le /g, 'Formats the '],
  [/formate le /g, 'formats the '],
  [/Applique le /g, 'Applies the '],
  [/applique le /g, 'applies the '],
  [/Active le /g, 'Enables the '],
  [/active le /g, 'enables the '],
  [/Désactive le /g, 'Disables the '],
  [/désactive le /g, 'disables the '],
  [/Envoie le /g, 'Sends the '],
  [/envoie le /g, 'sends the '],
  [/Stocke le /g, 'Stores the '],
  [/stocke le /g, 'stores the '],
  
  // Function descriptions in frontmatter - common patterns
  [/description: Ajoute un /g, 'description: Adds a '],
  [/description: Ajoute une /g, 'description: Adds an '],
  [/description: Crée un /g, 'description: Creates a '],
  [/description: Crée une /g, 'description: Creates a '],
  [/description: Définit l'/g, 'description: Sets the '],
  [/description: Définit le /g, 'description: Sets the '],
  [/description: Définit la /g, 'description: Sets the '],
  [/description: Retourne le /g, 'description: Returns the '],
  [/description: Retourne la /g, 'description: Returns the '],
  [/description: Permet de /g, 'description: Allows '],
  [/description: Permet d'/g, 'description: Allows '],
  [/description: Permet aux /g, 'description: Allows '],
  [/description: Récupère le /g, 'description: Retrieves the '],
  [/description: Récupère la /g, 'description: Retrieves the '],
  [/description: Supprime le /g, 'description: Deletes the '],
  [/description: Supprime la /g, 'description: Deletes the '],
  [/description: Vérifie si /g, 'description: Checks if '],
  [/description: Vérifie l'/g, 'description: Checks the '],
  [/description: Calcule le /g, 'description: Calculates the '],
  [/description: Mesure le /g, 'description: Measures the '],
  [/description: Convertit le /g, 'description: Converts the '],
  [/description: Formate le /g, 'description: Formats the '],
  [/description: Active le /g, 'description: Enables the '],
  [/description: Désactive le /g, 'description: Disables the '],
  [/description: Envoie le /g, 'description: Sends the '],
  [/description: Applique le /g, 'description: Applies the '],
  [/description: Combine le /g, 'description: Combines the '],
  [/description: Stocke le /g, 'description: Stores the '],
  [/description: Fournit le /g, 'description: Provides the '],
  [/description: Affiche le /g, 'description: Displays the '],
  [/description: Bannit un /g, 'description: Bans a '],
  [/description: Démarre une /g, 'description: Starts a '],
  [/description: Initialise un /g, 'description: Initializes a '],
  [/description: Initialise une /g, 'description: Initializes a '],
  [/description: Modifie le /g, 'description: Modifies the '],
  [/description: Modifie la /g, 'description: Modifies the '],
  [/description: Renomme le /g, 'description: Renames the '],
  [/description: Change le /g, 'description: Changes the '],
  
  // Number patterns
  [/Nombre minimum de salons/g, 'Minimum number of channels'],
  [/Nombre maximum de salons/g, 'Maximum number of channels'],
  [/Nombre minimum d'entités/g, 'Minimum number of entities'],
  [/Nombre maximum d'entités/g, 'Maximum number of entities'],
  [/Nombre minimum de rôles/g, 'Minimum number of roles'],
  [/Nombre maximum de rôles/g, 'Maximum number of roles'],
  [/Nombre minimum/g, 'Minimum number'],
  [/Nombre maximum/g, 'Maximum number'],
  [/nombre minimum/g, 'minimum number'],
  [/nombre maximum/g, 'maximum number'],
  [/Nombre de jours/g, 'Number of days'],
  [/Nombre de caractères/g, 'Number of characters'],
  
  // Obligatoire/Optionnel in text (not tables)
  [/Obligatoire\./g, 'Required.'],
  [/Optionnel\./g, 'Optional.'],
  [/obligatoire\./g, 'required.'],
  [/optionnel\./g, 'optional.'],
  
  // Aucun paramètre / Aucune
  [/Aucun paramètre\./g, 'No parameters.'],
  [/Aucun paramètre requis\./g, 'No parameters required.'],
  [/Aucun paramètre/g, 'No parameters'],
  [/Aucune\./g, 'None.'],
  [/Aucune valeur de retour\./g, 'No return value.'],
  [/Aucune valeur de retour/g, 'No return value'],
  
  // Common patterns with "est" / "sont"
  [/est un conteneur qui regroupe/g, 'is a container that groups'],
  [/est un conteneur/g, 'is a container'],
  [/est une chaîne/g, 'is a string'],
  [/est un entier/g, 'is an integer'],
  [/est un nombre/g, 'is a number'],
  [/est une valeur/g, 'is a value'],
  [/est une fonctionnalité/g, 'is a feature'],
  [/est conservé pour rétrocompatibilité/g, 'is kept for backward compatibility'],
  [/est conservé/g, 'is kept'],
  
  // French words that frequently remain
  [/appelée avant d'ajouter/g, 'called before adding'],
  [/appelée/g, 'called'],
  [/Appelée/g, 'Called'],
  [/ajoutés après seront placés/g, 'added after it will be placed'],
  [/ajoutés après/g, 'added afterward'],
  [/ajoutés/g, 'added'],
  [/Ajoutés/g, 'Added'],
  [/d'ajouter des /g, 'to add '],
  [/d'ajouter un /g, 'to add a '],
  [/d'ajouter une /g, 'to add a '],
  [/pour contenir des /g, 'to contain '],
  [/pour contenir/g, 'to contain'],
  [/pour organiser/g, 'to organize'],
  [/pour les organiser/g, 'to organize them'],
  [/organiser/g, 'organize'],
  [/sur des lignes distinctes/g, 'on distinct rows'],
  [/sur une même ligne/g, 'on the same row'],
  [/sur une ligne/g, 'on a row'],
  [/sur cette ligne/g, 'on that row'],
  [/sur la ligne/g, 'on the row'],
  [/sur le /g, 'on the '],
  [/sur la /g, 'on the '],
  [/sur l'/g, 'on the '],
  [/horizontale/g, 'horizontal'],
  [/horizontale dans/g, 'horizontal in'],
  [/ligne horizontale/g, 'horizontal row'],
  
  // Colors
  [/Couleur hex de la bordure/g, 'Hex color of the border'],
  [/Couleur hex/g, 'Hex color'],
  [/Couleur de la bordure/g, 'Color of the border'],
  [/Couleur d'accent/g, 'Accent color'],
  
  // Validation
  [/doit faire au moins (\d+) caractères/g, 'must be at least $1 characters'],
  [/doit faire (\d+) à (\d+) caractères/g, 'must be $1 to $2 characters'],
  [/doit contenir que des lettres/g, 'must only contain letters'],
  
  // Le bot patterns
  [/Le bot doit avoir la permission/g, 'The bot must have the permission'],
  [/Le bot doit avoir accès/g, 'The bot must have access'],
  [/Le bot ne peut pas/g, 'The bot cannot'],
  [/Le bot doit/g, 'The bot must'],
  [/le bot doit/g, 'the bot must'],
  
  // Utilisez/Privilégiez
  [/Utilisez `([^`]+)` pour distinguer/g, 'Use `$1` to distinguish'],
  [/Utilisez `([^`]+)` pour mentionner/g, 'Use `$1` to mention'],
  [/Utilisez `([^`]+)` pour /g, 'Use `$1` to '],
  [/Utilisez `([^`]+)`/g, 'Use `$1`'],
  [/utilisez `([^`]+)`/g, 'use `$1`'],
  [/Utilisez /g, 'Use '],
  [/utilisez /g, 'use '],
  [/Privilégiez `([^`]+)`/g, 'Prefer `$1`'],
  [/privilégiez `([^`]+)`/g, 'prefer `$1`'],
  [/Privilégiez /g, 'Prefer '],
  
  // Pour (reason/purpose)
  [/Pour bannir par ID/g, 'To ban by ID'],
  [/Pour modifier/g, 'To modify'],
  [/Pour les nouveaux bots/g, 'For new bots'],
  [/Pour les nouveaux développements/g, 'For new development'],
  [/Pour le message de réponse/g, 'For the response message'],
  [/Pour le message déclencheur/g, 'For the trigger message'],
  [/Pour le débogage/g, 'For debugging'],
  [/Pour la latence/g, 'For latency'],
  [/Pour des groupes/g, 'For groups'],
  [/Pour les commandes/g, 'For commands'],
  [/Pour réagir/g, 'To react'],
  [/Pour organiser/g, 'To organize'],
  
  // après coup
  [/après coup/g, 'afterward'],
  [/après avoir défini/g, 'after setting'],
  [/après l'envoi/g, 'after sending'],
  [/Après l'envoi/g, 'After sending'],
  
  // L'utilisateur
  [/L'utilisateur peut choisir/g, 'The user can choose'],
  [/L'utilisateur peut /g, 'The user can '],
  [/l'utilisateur clique/g, 'the user clicks'],
  [/l'utilisateur peut /g, 'the user can '],
  [/l'utilisateur doit /g, 'the user must '],
  
  // Table content specific
  [/\| Type de retour \|/g, '| Return type |'],
  [/\| Valeur de retour \|/g, '| Return value |'],
  
  // Ceci / Cela
  [/Ceci est /g, 'This is '],
  [/ceci est /g, 'this is '],
  [/Cela signifie /g, 'This means '],
  
  // H1 titles with French descriptions  
  [/^# \$(\w+)\n\nDémarre une /gm, '# $$$1\n\nStarts a '],
  [/^# \$(\w+)\n\nAjoute un /gm, '# $$$1\n\nAdds a '],
  [/^# \$(\w+)\n\nAjoute une /gm, '# $$$1\n\nAdds an '],
  [/^# \$(\w+)\n\nCrée un /gm, '# $$$1\n\nCreates a '],
  [/^# \$(\w+)\n\nCrée une /gm, '# $$$1\n\nCreates a '],
  [/^# \$(\w+)\n\nDéfinit /gm, '# $$$1\n\nSets '],
  [/^# \$(\w+)\n\nRetourne /gm, '# $$$1\n\nReturns '],
  [/^# \$(\w+)\n\nBannit /gm, '# $$$1\n\nBans '],
  [/^# \$(\w+)\n\nRécupère /gm, '# $$$1\n\nRetrieves '],
  [/^# \$(\w+)\n\nSupprime /gm, '# $$$1\n\nDeletes '],
  [/^# \$(\w+)\n\nVérifie /gm, '# $$$1\n\nChecks '],
  [/^# \$(\w+)\n\nMesure /gm, '# $$$1\n\nMeasures '],
  [/^# \$(\w+)\n\nCalcule /gm, '# $$$1\n\nCalculates '],
  [/^# \$(\w+)\n\nConvertit /gm, '# $$$1\n\nConverts '],
  [/^# \$(\w+)\n\nActive /gm, '# $$$1\n\nEnables '],
  [/^# \$(\w+)\n\nDésactive /gm, '# $$$1\n\nDisables '],
  [/^# \$(\w+)\n\nEnvoie /gm, '# $$$1\n\nSends '],
  [/^# \$(\w+)\n\nInitialise /gm, '# $$$1\n\nInitializes '],
  
  // Remaining single French words
  [/Démarre /g, 'Starts '],
  [/démarre /g, 'starts '],
  [/Appelé /g, 'Called '],
  [/appelé /g, 'called '],
  [/Ajouté /g, 'Added '],
  [/ajouté /g, 'added '],
  [/Créé /g, 'Created '],
  [/créé /g, 'created '],
  [/Modifié /g, 'Modified '],
  [/modifié /g, 'modified '],
  [/Supprimé /g, 'Deleted '],
  [/supprimé /g, 'deleted '],
  [/Exécuté /g, 'Executed '],
  [/exécuté /g, 'executed '],
  [/Sélectionné /g, 'Selected '],
  [/sélectionné /g, 'selected '],
  [/Récupéré /g, 'Retrieved '],
  [/récupéré /g, 'retrieved '],
  [/Envoyé /g, 'Sent '],
  [/envoyé /g, 'sent '],
  [/Stocké /g, 'Stored '],
  [/stocké /g, 'stored '],
  [/Fourni /g, 'Provided '],
  [/fourni /g, 'provided '],
  [/Mesuré /g, 'Measured '],
  [/mesuré /g, 'measured '],
  [/Affiché /g, 'Displayed '],
  [/affiché /g, 'displayed '],
  [/Désactivé /g, 'Disabled '],
  [/désactivé /g, 'disabled '],
  [/Activé /g, 'Enabled '],
  [/activé /g, 'enabled '],
  [/Défini /g, 'Set '],
  [/défini /g, 'set '],
  
  // More French words
  [/également /g, 'also '],
  [/Également /g, 'Also '],
  [/notamment /g, 'notably '],
  [/uniquement /g, 'only '],
  [/Uniquement /g, 'Only '],
  [/directement /g, 'directly '],
  [/Directement /g, 'Directly '],
  [/automatiquement /g, 'automatically '],
  [/Automatiquement /g, 'Automatically '],
  [/actuellement /g, 'currently '],
  [/Actuellement /g, 'Currently '],
  [/préalablement /g, 'previously '],
  [/rapidement /g, 'quickly '],
  [/simplement /g, 'simply '],
  [/complètement /g, 'completely '],
  [/temporairement /g, 'temporarily '],
  [/définitivement /g, 'permanently '],
  
  // Common remaining
  [/Longueur maximale : (\d+) caractères/g, 'Maximum length: $1 characters'],
  [/Longueur minimale : (\d+) caractères/g, 'Minimum length: $1 characters'],
  [/longueur maximale/g, 'maximum length'],
  [/longueur minimale/g, 'minimum length'],
  
  // Example subtitles
  [/### Ligne simple/g, '### Simple row'],
  [/### Avec ID personnalisé/g, '### With custom ID'],
  [/### Plusieurs lignes/g, '### Multiple rows'],
  [/### Auteur simple/g, '### Simple author'],
  [/### Auteur avec avatar/g, '### Author with avatar'],
  [/### Auteur avec lien cliquable/g, '### Author with clickable link'],
  [/### Bannissement simple avec mention/g, '### Simple ban with mention'],
  [/### Bannissement avec suppression de messages/g, '### Ban with message deletion'],
  [/### Command de bannissement avec confirmation/g, '### Ban command with confirmation'],
  [/### Affichage simple/g, '### Simple display'],
  [/### Footer dynamique/g, '### Dynamic footer'],
  [/### Condition de lenteur/g, '### Slowness condition'],
  [/### Bouton simple/g, '### Simple button'],
  [/### Bouton lien/g, '### Link button'],
  [/### Bouton désactivé/g, '### Disabled button'],
  [/### Nouvelle ligne avec deux boutons/g, '### New row with two buttons'],
  [/### Bouton désactivé avec emoji/g, '### Disabled button with emoji'],
  [/### Plusieurs boutons sur des lignes distinctes/g, '### Multiple buttons on distinct rows'],
  [/### Groupe de centres d'intérêt/g, '### Interests group'],
  [/### Groupe obligatoire/g, '### Required group'],
  [/### Récupération des valeurs/g, '### Retrieving values'],
  [/### Conteneur basique/g, '### Basic container'],
  [/### Conteneur avec couleur d'accent/g, '### Container with accent color'],
  [/### Conteneur spoiler/g, '### Spoiler container'],
  [/### Conteneurs multiples/g, '### Multiple containers'],
  [/### Avec menuId explicite/g, '### With explicit menuId'],
  [/### Sans menuId \(dernier groupe\)/g, '### Without menuId (last group)'],
  [/### Plusieurs groupes distincts/g, '### Multiple distinct groups'],
  [/### Galerie simple/g, '### Simple gallery'],
  [/### Galerie dans un conteneur/g, '### Gallery in a container'],
  [/### Galerie avec spoiler/g, '### Gallery with spoiler'],
  [/### Dans un embed complet/g, '### In a complete embed'],
  [/### Avec galleryId explicite/g, '### With explicit galleryId'],
  [/### Sans galleryId \(dernière galerie\)/g, '### Without galleryId (last gallery)'],
  [/### Plusieurs galeries distinctes/g, '### Multiple distinct galleries'],
  [/### Avec spoiler/g, '### With spoiler'],
  [/### Sélection simple/g, '### Simple selection'],
  [/### Sélection multiple/g, '### Multiple selection'],
  [/### Menu désactivé/g, '### Disabled menu'],
  [/### Salon textuel uniquement/g, '### Text channel only'],
  [/### Salons vocaux et scènes/g, '### Voice and stage channels'],
  [/### Sélection de salon/g, '### Channel selection'],
  [/### Ajout simple/g, '### Simple addition'],
  [/### Emoji avec pièce jointe/g, '### Emoji from attachment'],
  [/### Emoji restreint au staff/g, '### Staff-restricted emoji'],
  [/### Validation du nom/g, '### Name validation'],
  [/### Fields pleine largeur/g, '### Full-width fields'],
  [/### Fields inline/g, '### Inline fields'],
  [/### Mix inline et non-inline/g, '### Mixed inline and non-inline'],
  [/### Insertion à une position spécifique/g, '### Insert at a specific position'],
  [/### Joindre une image/g, '### Attach an image'],
  [/### Document PDF/g, '### PDF document'],
  [/### Fichier spoiler/g, '### Spoiler file'],
  [/### Fichiers multiples/g, '### Multiple files'],
  [/### Avec embed et fichier/g, '### With embed and file'],
  [/### Case à cocher simple/g, '### Simple checkbox'],
  [/### Vérification de l'état/g, '### State verification'],
  [/### Simple sélection/g, '### Simple selection'],
  [/### Sélection de rôle/g, '### Role selection'],
  [/### Rôles multiples/g, '### Multiple roles'],
  [/### Conteneur avec une section/g, '### Container with one section'],
  [/### Conteneur multi-sections/g, '### Multi-section container'],
  [/### Sections dans un message complexe/g, '### Sections in a complex message'],
  [/### Instructions dans un modal/g, '### Instructions in a modal'],
  [/### Informations formatées/g, '### Formatted information'],
  [/### Multiple text blocks/g, '### Multiple text blocks'],
  [/### Input with placeholder and default/g, '### Input with placeholder and default'],
  [/### Validation with length limits/g, '### Validation with length limits'],
  [/### Feedback silencieux/g, '### Silent feedback'],
  [/### Feedback conditionnel/g, '### Conditional feedback'],
  [/### Indicateur de progression/g, '### Progress indicator'],
  [/### Réagir à un message de rules/g, '### React to a rules message'],
  [/### Réaction à un message stocké/g, '### Reaction to a stored message'],
  [/### Réagir à un message de giveaway/g, '### React to a giveaway message'],
  [/### Simple reaction/g, '### Simple reaction'],
  [/### Conditional reactions/g, '### Conditional reactions'],
  
  // Final cleanup - single French articles that remain
  [/\bune action row/g, 'an action row'],
  [/\bune ligne/g, 'a row'],
  [/\bune valeur/g, 'a value'],
  [/\bune réponse/g, 'a response'],
  [/\bune icône/g, 'an icon'],
  [/\bune image/g, 'an image'],
  [/\bune URL/g, 'a URL'],
  [/\bune chaîne/g, 'a string'],
  [/\bune erreur/g, 'an error'],
  [/\bune fonction/g, 'a function'],
  [/\bune liste/g, 'a list'],
  [/\bune bordure/g, 'a border'],
  [/\bune galerie/g, 'a gallery'],
  [/\bune section/g, 'a section'],
  [/\bun message/g, 'a message'],
  [/\bun salon/g, 'a channel'],
  [/\bun rôle/g, 'a role'],
  [/\bun serveur/g, 'a server'],
  [/\bun embed/g, 'an embed'],
  [/\bun conteneur/g, 'a container'],
  [/\bun fichier/g, 'a file'],
  [/\bun bouton/g, 'a button'],
  [/\bun champ/g, 'a field'],
  [/\bun menu/g, 'a menu'],
  [/\bun groupe/g, 'a group'],
  [/\bun modal/g, 'a modal'],
  [/\bun composant/g, 'a component'],
  [/\bun utilisateur/g, 'a user'],
  [/\bun lien/g, 'a link'],
  [/\bun ID/g, 'an ID'],
  [/\bun nom/g, 'a name'],
  [/\bun emoji/g, 'an emoji'],
  [/\bun entier/g, 'an integer'],
  [/\bun délai/g, 'a delay'],
  [/\bun index/g, 'an index'],
  [/des boutons/g, 'buttons'],
  [/des composants/g, 'components'],
  [/des menus/g, 'menus'],
  [/des options/g, 'options'],
  [/des champs/g, 'fields'],
  [/des rôles/g, 'roles'],
  [/des salons/g, 'channels'],
  [/des messages/g, 'messages'],
  [/des utilisateurs/g, 'users'],
  [/des fichiers/g, 'files'],
  [/des images/g, 'images'],
  [/des réactions/g, 'reactions'],
  [/des emojis/g, 'emojis'],
  [/des données/g, 'data'],
  [/des variables/g, 'variables'],
  [/des valeurs/g, 'values'],
  [/des erreurs/g, 'errors'],
  [/des IDs/g, 'IDs'],
  
  // Last resort - remaining common French words
  [/d'exécution/g, 'execution'],
  [/d'exécuter/g, 'to execute'],
  [/l'exécution/g, 'the execution'],
  [/l'utilisateur/g, 'the user'],
  [/L'utilisateur/g, 'The user'],
  [/l'interface/g, 'the interface'],
  [/l'option/g, 'the option'],
  [/l'action/g, 'the action'],
  [/l'état/g, 'the state'],
  [/l'index/g, 'the index'],
  [/l'ID/g, 'the ID'],
  [/l'URL/g, 'the URL'],
  [/l'image/g, 'the image'],
  [/l'icône/g, 'the icon'],
  [/l'emoji/g, 'the emoji'],
  [/l'embed/g, 'the embed'],
  [/l'ordre/g, 'the order'],
  [/l'auteur/g, 'the author'],
  [/L'auteur/g, 'The author'],
  [/l'API/g, 'the API'],
  [/l'interaction/g, 'the interaction'],
  [/l'ensemble/g, 'the whole'],
  [/l'appel/g, 'the call'],
  [/d'erreur/g, 'error'],
  
  // Misc fixes
  [/\bdébogage\b/g, 'debugging'],
  [/\bDébogage\b/g, 'Debugging'],
  [/\bdéboguage\b/g, 'debugging'],
  [/\boptimisation\b/g, 'optimization'],
  [/\bOptimisation\b/g, 'Optimization'],
  [/\blatence\b/g, 'latency'],
  [/\bLatence\b/g, 'Latency'],
  [/\bréseau\b/g, 'network'],
  [/\bRéseau\b/g, 'Network'],
  [/\bperformances\b/g, 'performance'],
  [/\bPerformances\b/g, 'Performance'],
  [/\bparamètre\b/g, 'parameter'],
  [/\bParamètre\b/g, 'Parameter'],
  [/\bparamètres\b/g, 'parameters'],
  [/\bParamètres\b/g, 'Parameters'],
  [/\bfonction\b/g, 'function'],
  [/\bFonction\b/g, 'Function'],
  [/\bfonctions\b/g, 'functions'],
  [/\bFonctions\b/g, 'Functions'],
  [/\bcomportement\b/g, 'behavior'],
  [/\bComportement\b/g, 'Behavior'],
  [/\butilisation\b/g, 'usage'],
  [/\bUtilisation\b/g, 'Usage'],
  [/\bexemple\b/g, 'example'],
  [/\bExemple\b/g, 'Example'],
  [/\bexemples\b/g, 'examples'],
  [/\bExemples\b/g, 'Examples'],
  [/\bretour\b/g, 'return'],
  [/\bRetour\b/g, 'Return'],
  [/\bsyntaxe\b/g, 'syntax'],
  [/\bSyntaxe\b/g, 'Syntax'],
  [/\bdescription\b/g, 'description'],
  [/\bDescription\b/g, 'Description'],
  [/\bvaleur\b/g, 'value'],
  [/\bValeur\b/g, 'Value'],
  [/\btype\b/g, 'type'],
  [/\bType\b/g, 'Type'],
  [/\btypes\b/g, 'types'],
  [/\bTypes\b/g, 'Types'],
  [/\bindex\b/g, 'index'],
  [/\bIndex\b/g, 'Index'],
  [/\bposition\b/g, 'position'],
  [/\bPosition\b/g, 'Position'],
  
  // La/Le at sentence start
  [/^La command /gm, 'The command '],
  [/^La valeur /gm, 'The value '],
  [/^La fonction /gm, 'The function '],
  [/^Le temps /gm, 'The time '],
  [/^Le paramètre /gm, 'The parameter '],
  [/^Le message /gm, 'The message '],
  [/^Le bot /gm, 'The bot '],
  [/^Le serveur /gm, 'The server '],
  [/^Le nom /gm, 'The name '],
  [/^L'ordre /gm, 'The order '],
  [/^L'URL /gm, 'The URL '],
  [/^L'ID /gm, 'The ID '],
  [/^L'état /gm, 'The state '],
  [/^L'index /gm, 'The index '],
  
  // Remove trailing "de la command" type fragments
  [/ of the command de la command/g, ' of the command'],
  [/ of the command en cours/g, ' of the current command'],
  [/ of the command actuelle/g, ' of the current command'],
  [/ de la command/g, ' of the command'],
  [/ de la fonction/g, ' of the function'],
  [/ du serveur/g, ' of the server'],
  [/ du message/g, ' of the message'],
  [/ du bot/g, ' of the bot'],
  [/ du code/g, ' of the code'],
  [/ du traitement/g, ' of the processing'],
  [/ du groupe/g, ' of the group'],
  [/ du temps/g, ' of the time'],
  [/ du champ/g, ' of the field'],
  [/ du texte/g, ' of the text'],
  [/ du nom/g, ' of the name'],
  [/ du titre/g, ' of the title'],
  [/ du contenu/g, ' of the content'],
  [/ du salon/g, ' of the channel'],
  [/ du rôle/g, ' of the role'],
  [/ du fichier/g, ' of the file'],
  [/ du modal/g, ' of the modal'],
  
  // Que
  [/\bque des /g, 'only '],
  [/\bque le /g, 'only the '],
  [/\bque la /g, 'only the '],
  [/\bque l'/g, 'only the '],
  
  // Et
  [/\bet la /g, 'and the '],
  [/\bet le /g, 'and the '],
  [/\bet l'/g, 'and the '],
  [/\bet des /g, 'and '],
  [/\bet une /g, 'and a '],
  [/\bet un /g, 'and a '],
  [/\bEt la /g, 'And the '],
  [/\bEt le /g, 'And the '],
  
  // Ou
  [/\bou la /g, 'or the '],
  [/\bou le /g, 'or the '],
  [/\bou l'/g, 'or the '],
  [/\bou un /g, 'or a '],
  [/\bou une /g, 'or a '],
  [/\bou des /g, 'or '],
  [/\bOu la /g, 'Or the '],
  [/\bOu le /g, 'Or the '],
  
  // Chaque
  [/\bChaque message/g, 'Each message'],
  [/\bChaque ligne/g, 'Each row'],
  [/\bChaque composant/g, 'Each component'],
  [/\bChaque option/g, 'Each option'],
  [/\bChaque section/g, 'Each section'],
  [/\bChaque conteneur/g, 'Each container'],
  [/\bChaque champ/g, 'Each field'],
  [/\bChaque fois/g, 'Each time'],
  [/\bChaque /g, 'Each '],
  [/\bchaque /g, 'each '],
  
  // Tous/Toutes
  [/\bTous les /g, 'All '],
  [/\bToutes les /g, 'All '],
  [/\btous les /g, 'all '],
  [/\btoutes les /g, 'all '],
  
  // Plusieurs
  [/\bPlusieurs /g, 'Multiple '],
  [/\bplusieurs /g, 'multiple '],
  
  // Pas
  [/\bne pas /g, 'not '],
  [/\bpas de /g, 'no '],
  [/\bpas les deux/g, 'not both'],
  [/\bpas la /g, 'not the '],
  [/\bpas le /g, 'not the '],
  [/\bpas l'/g, 'not the '],
  
  // Common hybrid fragments  
  [/de la current command/g, 'of the current command'],
  [/de messages/g, 'of messages'],
  [/de l'utilisateur/g, 'of the user'],
  [/de performance/g, 'of performance'],
  [/à supprimer/g, 'to delete'],
  [/à sélectionner/g, 'to select'],
  [/à afficher/g, 'to display'],
  [/à ajouter/g, 'to add'],
  [/à utiliser/g, 'to use'],
  [/à bannir/g, 'to ban'],
  [/à récupérer/g, 'to retrieve'],
  [/à modifier/g, 'to modify'],
  [/à exécuter/g, 'to execute'],
  [/à envoyer/g, 'to send'],
  [/à désactiver/g, 'to disable'],
  [/à activer/g, 'to enable'],
  [/à supprimer/g, 'to delete'],
  [/à créer/g, 'to create'],
  [/à cibler/g, 'to target'],
  [/à définir/g, 'to set'],
  
  // Entier
  [/\bentier /g, 'integer '],
  [/\bEntier /g, 'Integer '],
  
  // représente
  [/\breprésentant /g, 'representing '],
  [/\breprésente /g, 'represents '],
  
  // contient
  [/\bcontient /g, 'contains '],
  [/\bContient /g, 'Contains '],
  
  // peut inclure
  [/\bpeut inclure /g, 'can include '],
  [/\bPeut inclure /g, 'Can include '],
  
  // ainsi
  [/\bainsi /g, 'thus '],
  [/\bAinsi /g, 'Thus '],
  
  // tel que
  [/\btel que /g, 'such as '],
  [/\btels que /g, 'such as '],
  [/\btelle que /g, 'such as '],
  
  // c'est-à-dire
  [/\bc'est-à-dire /g, 'i.e. '],
  
  // car
  [/\bcar /g, 'because '],
  [/\bCar /g, 'Because '],
  
  // donc
  [/\bdonc /g, 'therefore '],
  [/\bDonc /g, 'Therefore '],
  
  // Final misc cleanups
  [/à la fin\./g, 'to the end.'],
  [/à la fin /g, 'to the end '],
  [/tout début/g, 'very beginning'],
  [/au début/g, 'at the beginning'],
  [/Au début/g, 'At the beginning'],
  [/au sien/g, 'its own'],
  [/par ID/g, 'by ID'],
  [/par nom/g, 'by name'],
  [/par défaut/g, 'by default'],
  [/of the server Discord/g, 'of the Discord server'],
  [/from the server Discord/g, 'from the Discord server'],
  [/in the server Discord/g, 'in the Discord server'],
  [/of the code BDFD/g, 'of the BDFD code'],
  [/du code BDFD/g, 'of the BDFD code'],
  
  // Specific file fixes
  [/The `\$executionTime` allows mesurer le temps d'execution total de la command in progress, in milliseconds\./g, 'The `$executionTime` function measures the total execution time of the current command, in milliseconds.'],
  [/The `\$executionTime` function mesurer the time d'execution total de la command in progress, in milliseconds\./g, 'The `$executionTime` function measures the total execution time of the current command, in milliseconds.'],
  [/La fonction `\$ban` \*\*bannit a user\*\* of the server Discord\./g, 'The `$ban` function **bans a user** from the Discord server.'],
  [/La fonction `\$unban` \*\*débannit a user\*\*/g, 'The `$unban` function **unbans a user**'],
  [/La fonction `\$kick` \*\*expulse a user\*\*/g, 'The `$kick` function **kicks a user**'],
  [/La fonction `\$mute` \*\*rend muet a user\*\*/g, 'The `$mute` function **mutes a user**'],
  [/La fonction `([^`]+)` \*\*([^*]+)\*\* of the server Discord\./g, 'The `$1` function **$2** from the Discord server.'],
  [/Auca parameter\./g, 'No parameters.'],
  
  // H1 cleanup
  [/^# \$(\w+) — (.+)$/gm, (match, func, desc) => {
    // Already in English, keep
    return `# $${func} — ${desc}`;
  }],
];

let count = 0;

for (const file of files) {
  const filePath = path.join(docsDir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  
  // Check if still has French
  const hasFrench = /[éèêëàâîïôûùçÉÈÊËÀÂÎÏÔÛÙÇ]/.test(content);
  if (!hasFrench) continue;
  
  let modified = false;
  for (const [pattern, replacement] of fixes) {
    const before = content;
    content = content.replace(pattern, replacement);
    if (content !== before) modified = true;
  }
  
  if (modified) {
    fs.writeFileSync(filePath, content, 'utf8');
    count++;
    console.log(`FIXED: ${file}`);
  }
}

console.log(`\nFixed ${count} files`);
