/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './_layouts/**/*.html',
    './_includes/**/*.html',
    './_posts/**/*.{html,md}',
    './_docs/**/*.{html,md}',
    './docs/**/*.html',
    './fr/**/*.{html,md}',
    './*.md',
    './*.html',
    './blog/**/*.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Linear.app / MongoDB-inspired corporate dark palette
        "primary":                   "#7c8aff",
        "on-primary":                "#ffffff",
        "primary-container":         "#2e3192",
        "on-primary-container":      "#c0c1ff",
        "primary-fixed":             "#e1e0ff",
        "primary-fixed-dim":         "#c0c1ff",
        "secondary":                 "#8b949e",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#21262d",
        "on-secondary-container":    "#c9d1d9",
        "secondary-fixed":           "#30363d",
        "secondary-fixed-dim":       "#21262d",
        "tertiary":                  "#0d1117",
        "on-tertiary":               "#c9d1d9",
        "tertiary-container":        "#161b22",
        "on-tertiary-container":     "#8b949e",
        "background":                "#0d1117",
        "on-background":             "#c9d1d9",
        "surface":                   "#0d1117",
        "on-surface":                "#c9d1d9",
        "surface-variant":           "#21262d",
        "on-surface-variant":        "#8b949e",
        "surface-container":         "#1c2128",
        "surface-container-low":     "#161b22",
        "surface-container-lowest":  "#0d1117",
        "surface-container-high":    "#21262d",
        "surface-container-highest": "#292e36",
        "outline":                   "#30363d",
        "outline-variant":           "#21262d",
        "inverse-surface":           "#c9d1d9",
        "inverse-on-surface":        "#0d1117",
        "error":                     "#f85149",
        "on-error":                  "#ffffff",
        "error-container":           "#490202",
        "on-error-container":        "#ffdad6",
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "sans":    ["Inter", "sans-serif"],
        "mono":    ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "2px",
        "lg":      "4px",
        "xl":      "8px",
        "full":    "12px",
      },
      boxShadow: {
        'neon':        '0 1px 3px rgba(124, 138, 255, 0.08), 0 1px 2px rgba(0, 0, 0, 0.3)',
        'neon-strong': '0 2px 8px rgba(124, 138, 255, 0.12), 0 2px 4px rgba(0, 0, 0, 0.4)',
      },
      spacing: {
        'xs':     '8px',
        'sm':     '16px',
        'md':     '24px',
        'lg':     '48px',
        'xl':     '80px',
        'gutter': '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
