/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './_layouts/**/*.html',
    './_includes/**/*.html',
    './_posts/**/*.{html,md}',
    './_docs/**/*.{html,md}',
    './docs/**/*.html',
    './fr/**/*.{html,md}',
    './*.md',
    './*.html',
    './blog/**/*.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Bot Creator Mobile Design System Tokens (AppTheme)
        "brand-primary":             "#6A0FA2",
        "brand-secondary":           "#9B30FF",
        "brand-purple-soft":         "#B19DF7",
        "primary":                   "#B19DF7",
        "primary-vibrant":           "#9B30FF",
        "primary-dark":              "#6A0FA2",
        "on-primary":                "#111111",
        "primary-container":         "#231536",
        "on-primary-container":      "#eaddfe",
        "primary-fixed":             "#eaddfe",
        "primary-fixed-dim":         "#b19df7",
        "secondary":                 "#888888",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#262626",
        "on-secondary-container":    "#f0f0f0",
        "secondary-fixed":           "#333333",
        "secondary-fixed-dim":       "#262626",
        "tertiary":                  "#111111",
        "on-tertiary":               "#f0f0f0",
        "tertiary-container":        "#151515",
        "on-tertiary-container":     "#888888",
        "background":                "#0D0D0F",
        "on-background":             "#EDEDF0",
        "surface":                   "#0D0D0F",
        "on-surface":                "#EDEDF0",
        "surface-variant":           "#1F1F25",
        "on-surface-variant":        "#A1A1AB",
        "surface-container":         "#17171B",
        "surface-container-low":     "#121215",
        "surface-container-lowest":  "#0A0A0C",
        "surface-container-high":    "#1F1F25",
        "surface-container-highest": "#26262D",
        "outline":                   "#2A2A31",
        "outline-variant":           "#232329",
        "outline-ghost":             "#33333B",
        "inverse-surface":           "#f0f0f0",
        "inverse-on-surface":        "#111111",
        "error":                     "#FF4D4D",
        "on-error":                  "#ffffff",
        "error-container":           "#401212",
        "on-error-container":        "#ffdad6",
        "online":                    "#10B981",
        "warning":                   "#FFA726",
        "info":                      "#1976D2",
        "gold":                      "#FFC107",
        // Discord UI simulator colors
        "discord":                   "#5865F2",
        "discord-light":             "#7983F5",
        "discord-dark-bg":           "#2B2D31",
        "discord-darker-bg":         "#1E1F22",
        "discord-border":            "#404249",
        "discord-text":              "#DBDEE1",
        "discord-muted":             "#949BA4",
        // Mobile Block category colors
        "block-messages":            "#2E7D32",
        "block-reactions":           "#FFA726",
        "block-channels":            "#1976D2",
        "block-moderation":          "#FF4D4D",
        "block-components":          "#38BDF8",
        "block-webhooks":            "#009688",
        "block-guild":               "#7986CB",
        "block-http":                "#00BCD4",
        "block-workflows":           "#FF6E40",
        "block-logic":               "#E91E63",
        "block-interactions":        "#FFC107",
        "block-music":               "#AEEA00",
      },
      fontFamily: {
        "display": ["Geist", "system-ui", "sans-serif"],
        "sans":    ["Geist", "system-ui", "sans-serif"],
        "mono":    ["Geist Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        "xs":      "4px",
        "sm":      "8px",
        "DEFAULT": "8px",
        "md":      "10px",
        "lg":      "12px",
        "xl":      "12px",
        "card":    "16px",
        "full":    "9999px",
      },
      boxShadow: {
        'brand':        'none',
        'brand-strong': 'none',
        'neon':         'none',
        'neon-strong':  '0 8px 24px rgba(0, 0, 0, 0.45)',
        'card':         'none',
      },
      spacing: {
        'xs':     '8px',
        'sm':     '16px',
        'md':     '24px',
        'lg':     '48px',
        'xl':     '80px',
        'gutter': '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
